##### Adding by SPC v{{ version_spc }}
##### secured-pc ##### auteur: L. Delatte, 2024

apiVersion: v1
kind: Pod
metadata:
  name: pk-ff-ach
  label:
    pgm: ff
spec:
  containers:
  - name: pk-ff-ach
    image: ldelatte/alpff:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: PULSE_SERVER
      value: unix:/tmp/.X11-unix/P{{ ansible_facts.user_uid }}
    # ports:
    volumeMounts:
    - name: vn-ffa-X11
      mountPath: /tmp/.X11-unix
      readOnly: true
    - name: vn-ffa-mozilla
      mountPath: /home/user/.mozilla
      readOnly: false
    - name: vn-ffa-cache
      mountPath: /home/user/.cache
      readOnly: false
    - name: vn-ffa-config
      mountPath: /home/user/.config
      readOnly: false
    - name: vn-ffa-tele
      mountPath: /home/user/Téléchargements
      readOnly: false
    - name: vn-ffa-fonts
      mountPath: /usr/share/fonts
      readOnly: true
    - name: vn-ffa-video
      mountPath: /dev/video0
      readOnly: true
    # command:
    # args:
    resources:
      requests:
        mem: 70M
        cpu: 90Mi
    # livenessProbe:
    securityContext:
      runAsUser: {{ ff_user }}
      runAsGroup: {{ ff_user }}
      fsGroup: {{ ff_user }}
      priviledged: False
      allowPrivilegeEscalation: False
      readOnlyRootFilesystem: True
      capabilities:
      seccompProfile:
        type:
      seLinuxOptions:
        user:
        role:
        type:
        level: "{{ se_ct_level.ff }}"
      procMount:
      sysctls:
        name:
  volumes:
  - name: vn-ffa-X11
    hostPath:
      path: /tmp/.X11-unix
      type: Directory
  - name: vn-ffa-mozilla
    hostPath:
      path: {{ ansible_user_dir }}/.config/mozilla-ach
      type: Directory
  - name: vn-ffa-cache
    emptyDir:
      sizeLimit: 300Mi
  - name: vn-ffa-config
    emptyDir:
      sizeLimit: 20Mi
  - name: vn-ffa-tele
    hostPath:
      path: {{ ansible_user_dir }}/Téléchargements/FF-ach
      type: Directory
  - name: vn-ffa-fonts
    hostPath:
      path: /usr/share/fonts
      type: Directory
  - name: vn-ffa-video
    hostPath:
      path: /dev/video0
      type: CharDevice
  restartPolicy: Never
  terminationGracePeriodSeconds: 3
  hostNetwork: False
  hostPID: False
  hostIPC: False

##### Added by SPC v{{ version_spc }}
