##### Adding by SPC v{{ version_spc }}
##### secured-pc ##### auteur: L. Delatte, 2024

apiVersion: v1
kind: Pod
metadata:
  name: pk-glances
  label:
    pgm: glances
spec:
  containers:
  - name: pk-glances
    image: ldelatte/glances:latest
    imagePullPolicy: IfNotPresent
    # env:
    # ports:
    volumeMounts:
    - name: vn-gl-release
      mountPath: /etc/os-release
      readOnly: true
    # command:
    # args:
    resources:
      requests:
        mem: 30M
        cpu: 20Mi
    # livenessProbe:
    securityContext:
      runAsUser: {{ gl_user }}
      runAsGroup: {{ gl_user }}
      fsGroup: {{ gl_user }}
      priviledged: False
      allowPrivilegeEscalation: False
      readOnlyRootFilesystem: True
      capabilities:
      seccompProfile:
        type:
      seLinuxOptions:
        user:
        role:
        type:
        level:
      procMount:
      sysctls:
        name:
  volumes:
  - name: vn-gl-release
    hostPath:
      path: /etc/os-release
      type: Directory
  restartPolicy: Never
  terminationGracePeriodSeconds: 3
  hostNetwork: True
  hostPID: True
  hostIPC: False

##### Added by SPC v{{ version_spc }}
