##### secured-pc ##### auteur: L. Delatte, 2024

- name: Playbook core all
  hosts: '{{target|default("localhost.localdomain")}}'
  become_method: ansible.builtin.sudo
  become: false
  vars_prompt:
   - name: ansible_become_pass
     prompt: For sudo cmds, what is your password ?
     private: true
  roles:
   - role: system
   - role: isolation
   - role: clamav
   - role: sshd
   - role: xterm
   - role: firefox
   - role: libreoffice
   - role: viewer
   - role: glances
