##### Adding by SPC v{{ version_spc }}
##### secured-pc ##### auteur: Laurent Delatte, 2024

apiVersion: v1
kind: Pod
metadata:
  name: pk-chrome
  label:
    pgm: chrome
spec:
  containers:
  - name: pk-chrome
    image: ldelatte/chrome:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: PULSE_SERVER
      value: "tcp:MAIN_IP:33500"
    # ports:
    volumeMounts:
    - name: vn-cho-config
      mountPath: /home/user/.config
      readOnly: False
    - name: vn-cho-cache
      mountPath: /home/user/.cache
      readOnly: False
    - name: vn-cho-local
      mountPath: /home/user/.local
      readOnly: False
    - name: vn-cho-pki
      mountPath: /home/user/.pki
      readOnly: False
    - name: vn-cho-shm
      mountPath: /dev/shm
      readOnly: false
    - name: vn-cho-video
      mountPath: /dev/video0
      readOnly: true
    - name: vn-cho-tele
      mountPath: /home/user/doc
      readOnly: false
    # command:
    # args:
    resources:
      requests:
        mem: 200M
        cpu: 100Mi
    # livenessProbe:
    securityContext:
      runAsUser: {{ ch_user }}
      runAsGroup: {{ ch_user }}
      fsGroup: {{ ch_user }}
      priviledged: False
      allowPrivilegeEscalation: False
      readOnlyRootFilesystem: True
      capabilities:
      seccompProfile:
        type:
      seLinuxOptions:
        user:
        role:
        type:
        level: "{{ se_ct_level.ch }}"
      procMount:
      sysctls:
        name:
  volumes:
  - name: vn-cho-config
    hostPath:
      path: {{ ansible_user_dir }}/.config/chrome
      type: Directory
  - name: vn-cho-cache
    emptyDir:
      sizeLimit: 200Mi
  - name: vn-cho-local
    emptyDir:
      sizeLimit: 20Mi
  - name: vn-cho-pki
    emptyDir:
      sizeLimit: 20Mi
  - name: vn-cho-shm
    emptyDir:
      sizeLimit: 999Mi
  - name: vn-cho-video
    hostPath:
      path: /dev/video0
      type: CharDevice
  - name: vn-cho-tele
    hostPath:
      path: {{ ansible_user_dir }}/Téléchargements/chrome
      type: Directory
  restartPolicy: Never
  terminationGracePeriodSeconds: 3
  # hostNetwork: False
  hostNetwork: True
  hostPID: False
  hostIPC: False

##### Added by SPC v{{ version_spc }}
