##### secured-pc ##### auteur: Laurent Delatte, 2024
# configure xterm environment

- block:

  - name: xterm dirs
    file:
      path: "{{ ansible_user_dir }}/Téléchargements/xterm"
      state: directory
      owner: "{{ xt_ct_user }}"
      group: "{{ ansible_user }}"
      seuser: "{{ se_ct_user }}"
      serole: "{{ se_ct_role }}"
      setype: "{{ se_ct_type }}"
      selevel: "{{ se_ct_level.xt }}"
      mode: 0770

  become: yes

- name: local xterm exec
  template:
    src: xterm.sh
    dest: "{{ local_bin_dir }}/xterm.sh"
    mode: 0540
- template:
    src: spc.core.xterm.desktop
    dest: "{{ ansible_user_dir }}/.local/share/applications/spc.core.xterm.desktop"
    mode: 0640
- template:
    src: pod-xterm.yml
    dest: "{{ pods_dir }}/pod-xterm.yml"
    mode: 0440
- command: podman pull docker.io/ldelatte/xterm
- debug:
    msg:
    - 
    - 
    - A SElinux config must be performed for xterm like this;
    - give a simple try to launch xterm, which shouldn't work, like this;   xterm
    - Then configure SElinux as root like this;
    - su -;  ./spc-selConfig.sh xterm    then follow displayed instructions.
    - 
    - 

