##### Adding by SPC v{{ version_spc }}
##### secured-pc ##### auteur: L. Delatte, 2024

apiVersion: v1
kind: Pod
metadata:
  name: pk-librof
  label:
    pgm: libreoffice
spec:
  containers:
  - name: pk-librof
    image: lscr.io/linuxserver/libreoffice:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: PUID
      value: {{ ff_user }}
    - name: PGID
      value: {{ ff_user }}
    volumeMounts:
    - name: vn-lo-config
      mountPath: /config
      readOnly: false
    - name: vn-lo-tele
      mountPath: /config/doc
      readOnly: false
    # command:
    # args:
    resources:
      requests:
        mem: 100M
        cpu: 100Mi
    # livenessProbe:
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      priviledged: True
      allowPrivilegeEscalation: False
      readOnlyRootFilesystem: False
      capabilities:
      # seccompProfile: type: unconfined #optional
      seccompProfile:
        type:
      seLinuxOptions: # tint2 !! ???
        user:
        role:
        type:
        level: "{{ se_ct_level.lo }}"
      procMount:
      sysctls:
        name:
  - name: pk-ff-tec
    image: ldelatte/alpff:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: DISPLAY
      value: ":22"
    # ports:
    volumeMounts:
    - name: vn-ffl-X11
      mountPath: /tmp/.X11-unix
      readOnly: true
    - name: vn-ffl-mozilla
      mountPath: /home/user/.mozilla
      readOnly: false
    - name: vn-ffl-cache
      mountPath: /home/user/.cache
      readOnly: false
    - name: vn-ffl-config
      mountPath: /home/user/.config
      readOnly: false
    - name: vn-lo-tele
      mountPath: /home/user/Téléchargements
      readOnly: false
    - name: vn-ffl-fonts
      mountPath: /usr/share/fonts
      readOnly: true
    command:
    - "/bin/sleep"
    - "60000"
    # args:
    resources:
      requests:
        mem: 70M
        cpu: 90Mi
    # livenessProbe:
    securityContext:
      runAsUser: {{ ff_user }}
      runAsGroup: {{ ff_user }}
      fsGroup: {{ ff_user }}
      priviledged: False
      allowPrivilegeEscalation: False
      readOnlyRootFilesystem: True
      capabilities:
      seccompProfile:
        type:
      seLinuxOptions:
        user:
        role:
        type:
        level: "{{ se_ct_level.lo }}"
      procMount:
      sysctls:
        name:
  volumes:
  - name: vn-lo-config
    hostPath:
      path: {{ ansible_user_dir }}/.config/libreoffice
      type: Directory
  - name: vn-lo-tele
    hostPath:
      path: {{ ansible_user_dir }}/Téléchargements/libreoffice
      type: Directory
  - name: vn-ffl-X11
    hostPath:
      path: /tmp/.X11-unix
      type: Directory
  - name: vn-ffl-mozilla
    hostPath:
      path: {{ ansible_user_dir }}/.config/mozilla-lbo
      type: Directory
  - name: vn-ffl-cache
    emptyDir:
      sizeLimit: 200Mi
  - name: vn-ffl-config
    emptyDir:
      sizeLimit: 200Mi
  - name: vn-ffl-fonts
    hostPath:
      path: /usr/share/fonts
      type: Directory
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  hostNetwork: False
  hostPID: False
  hostIPC: False

##### Added by SPC v{{ version_spc }}
