##### secured-pc ##### auteur: Laurent Delatte, 2024
# configure isolation environment

- block:

  - name: deactivate rpcbind
    command: systemctl disable --now rpcbind.target

  - name: fw config
    command: cp -p /etc/firewalld/zones/public.xml /etc/firewalld/zones/public.xml.0
    args:
      creates: /etc/firewalld/zones/public.xml.0
  - copy:
      src: public_loc.xml
      dest: /etc/firewalld/zones/public.xml
      mode: 0640
    when: ansible_connection == "local"
  - copy:
      src: public_cli.xml
      dest: /etc/firewalld/zones/public.xml
      mode: 0640
    when: ansible_connection != "local"
  - copy:
      src: sortie.xml
      dest: /etc/firewalld/policies/spc-sortie.xml
      mode: 0640
  - copy:
      src: sshd-ct.xml
      dest: /etc/firewalld/services/spc-sshd-ct.xml
      mode: 0640
  - copy:
      src: printer.xml
      dest: /etc/firewalld/services/spc-printer.xml
      mode: 0640
  - copy:
      src: dhcp-kvm.xml
      dest: /etc/firewalld/services/spc-dhcp-kvm.xml
      mode: 0640
  - command: firewall-cmd --reload
  - command: firewall-cmd --zone=libvirt --add-service=spc-sshd-ct --permanent
    when: ansible_connection == "local"

  - name: selinux config
    template:
      src: selConfig.sh
      dest: /root/spc-selConfig.sh
      mode: 0700

  become: yes

- template:
    src: infNetSys.sh
    dest: "{{ ansible_user_dir }}/.config/infNetSys.sh"
    mode: 0740
- name: creates the dedicated pods local networks
  command: sh -c "{{ ansible_user_dir }}/.config/infNetSys.sh"

- debug:
    msg:
    - 
    - 
    - A particular isolation (re)apply is to perform after, in case of other isolation role.
    - 
    - 
