##### secured-pc ##### auteur: Laurent Delatte, 2024

- hosts: '{{target|default("localhost.localdomain")}}'
  become_method: sudo
  become: no
  vars_prompt:
  - name: ansible_become_pass
    prompt: For sudo cmds, what is your password ?
    private: true
  roles:
  - role: onedrive
  - role: chrome
