##### secured-pc ##### auteur: Laurent Delatte, 2024
# configure glances environment

- block:

  - name: create a system view user
    group:
      name: sysview
      state: present
      gid: "{{ gl_user }}"
  - user:
      name: sysview
      state: present
      comment: "system view user"
      uid: "{{ gl_user }}"
      group: sysview
      create_home: false
      groups: "adm,systemd-journal"
      password_lock: yes
      shell: /sbin/nologin

  become: yes

- name: local glances exec
  template:
    src: glances.sh
    dest: "{{ local_bin_dir }}/glances.sh"
    mode: 0540
- template:
    src: spc.core.glances.desktop
    dest: "{{ ansible_user_dir }}/.local/share/applications/spc.core.glances.desktop"
    mode: 0640
- template:
    src: pod-glances.yml
    dest: "{{ pods_dir }}/pod-glances.yml"
    mode: 0440
